default: &default
  adapter: postgis
  encoding: unicode
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: postgis_app_development

test:
  <<: *default
  database: postgis_app_test

production:
  <<: *default
  database: postgis_app_production
  username: postgis_app
  password: <%= ENV["POSTGIS_APP_DATABASE_PASSWORD"] %>
